CREATE TABLE users (
    id BIGINT NOT NULL COMMENT '用户编号',
    status TINYINT NOT NULL COMMENT '状态',
    last_login_at DATETIME(3) NULL COMMENT '最近登录',
    deactivated_at DATETIME(3) NULL COMMENT '注销时间',
    version INT NOT NULL COMMENT '版本',
    created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL COMMENT '更新时间',
    PRIMARY KEY(id),
    KEY idx_users_status_created(status,
        created_at,
        id),
    CONSTRAINT chk_users_status CHECK(status IN(1,
        2,
        3,
        4)),
    CONSTRAINT chk_users_version CHECK(version>=0),
    CONSTRAINT chk_users_deactivated CHECK((status=3 AND deactivated_at IS NOT NULL) OR(status<>3 AND deactivated_at IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户身份根和账号生命周期';

CREATE TABLE file_objects (
    id BIGINT NOT NULL COMMENT '文件编号',
    uploader_type TINYINT NOT NULL COMMENT '来源类型',
    uploader_id BIGINT NOT NULL COMMENT '来源编号',
    storage_provider VARCHAR(32) NOT NULL COMMENT '存储服务商',
    bucket_name VARCHAR(128) NOT NULL COMMENT '存储桶',
    object_key VARCHAR(512) NOT NULL COMMENT '对象键',
    original_filename VARCHAR(255) NOT NULL COMMENT '原始文件名',
    content_type VARCHAR(128) NOT NULL COMMENT '内容类型',
    file_extension VARCHAR(32) NOT NULL COMMENT '扩展名',
    size_bytes BIGINT NOT NULL COMMENT '大小',
    sha256 BINARY(32) NOT NULL COMMENT '摘要',
    access_level TINYINT NOT NULL COMMENT '访问级别',
    scan_status TINYINT NOT NULL COMMENT '检查状态',
    lifecycle_status TINYINT NOT NULL COMMENT '生命周期',
    expires_at DATETIME(3) NULL COMMENT '过期时间',
    activated_at DATETIME(3) NULL COMMENT '生效时间',
    deleted_at DATETIME(3) NULL COMMENT '删除时间',
    version INT NOT NULL COMMENT '版本',
    created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL COMMENT '更新时间',
    PRIMARY KEY(id),
    UNIQUE KEY uk_file_object_key(object_key),
    KEY idx_file_lifecycle_expire(lifecycle_status,
        expires_at,
        id),
    KEY idx_file_uploader_created(uploader_type,
        uploader_id,
        created_at,
        id),
    KEY idx_file_sha256(sha256),
    CONSTRAINT chk_file_type CHECK(uploader_type IN(1,
        2,
        3)),
    CONSTRAINT chk_file_size CHECK(size_bytes>0),
    CONSTRAINT chk_file_access CHECK(access_level IN(1,
        2,
        3)),
    CONSTRAINT chk_file_scan CHECK(scan_status IN(1,
        2,
        3)),
    CONSTRAINT chk_file_lifecycle CHECK(lifecycle_status IN(1,
        2,
        3)),
    CONSTRAINT chk_file_version CHECK(version>=0),
    CONSTRAINT chk_file_deleted CHECK((lifecycle_status=3 AND deleted_at IS NOT NULL) OR(lifecycle_status<>3 AND deleted_at IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文件元数据、访问和生命周期';

CREATE TABLE user_wechat_accounts (
    id BIGINT NOT NULL COMMENT '绑定编号',
    user_id BIGINT NOT NULL COMMENT '用户编号',
    app_id VARCHAR(128) NOT NULL COMMENT '应用编号',
    openid_ciphertext VARBINARY(1024) NOT NULL COMMENT '加密标识',
    openid_lookup_hash BINARY(32) NOT NULL COMMENT '查找摘要',
    unionid_ciphertext VARBINARY(1024) NULL COMMENT '加密联合标识',
    unionid_lookup_hash BINARY(32) NULL COMMENT '联合查找摘要',
    status TINYINT NOT NULL COMMENT '状态',
    bound_at DATETIME(3) NOT NULL COMMENT '绑定时间',
    unbound_at DATETIME(3) NULL COMMENT '解绑时间',
    last_login_at DATETIME(3) NULL COMMENT '最近登录',
    created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL COMMENT '更新时间',
    active_openid_lookup_hash BINARY(32) GENERATED ALWAYS AS(IF(status=1,
        openid_lookup_hash,
        NULL)) STORED COMMENT '有效摘要',
    active_user_app TINYINT GENERATED ALWAYS AS(IF(status=1,
        1,
        NULL)) STORED COMMENT '有效标记',
    PRIMARY KEY(id),
    UNIQUE KEY uk_wechat_active_identity(app_id,
        active_openid_lookup_hash),
    UNIQUE KEY uk_wechat_active_user_app(user_id,
        app_id,
        active_user_app),
    KEY idx_wechat_user_status_login(user_id,
        status,
        last_login_at,
        id),
    CONSTRAINT fk_wechat_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_wechat_status CHECK(status IN(1,
        2)),
    CONSTRAINT chk_wechat_unbound CHECK((status=1 AND unbound_at IS NULL) OR(status=2 AND unbound_at IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='微信小程序身份绑定';

CREATE TABLE user_phone_bindings (
    id BIGINT NOT NULL COMMENT '绑定编号',
    user_id BIGINT NOT NULL COMMENT '用户编号',
    country_code VARCHAR(8) NOT NULL COMMENT '地区代码',
    phone_ciphertext VARBINARY(1024) NOT NULL COMMENT '加密手机号',
    phone_lookup_hash BINARY(32) NOT NULL COMMENT '手机号摘要',
    phone_last_four CHAR(4) NOT NULL COMMENT '后四位',
    status TINYINT NOT NULL COMMENT '状态',
    bound_at DATETIME(3) NOT NULL COMMENT '绑定时间',
    unbound_at DATETIME(3) NULL COMMENT '解绑时间',
    unbind_reason VARCHAR(64) NULL COMMENT '解绑原因',
    created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL COMMENT '更新时间',
    active_user TINYINT GENERATED ALWAYS AS(IF(status=1,
        1,
        NULL)) STORED COMMENT '有效用户',
    active_phone_lookup_hash BINARY(32) GENERATED ALWAYS AS(IF(status=1,
        phone_lookup_hash,
        NULL)) STORED COMMENT '有效摘要',
    PRIMARY KEY(id),
    UNIQUE KEY uk_phone_active_user(user_id,
        active_user),
    UNIQUE KEY uk_phone_active_number(country_code,
        active_phone_lookup_hash),
    KEY idx_phone_user_status_bound(user_id,
        status,
        bound_at,
        id),
    CONSTRAINT fk_phone_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_phone_status CHECK(status IN(1,
        2)),
    CONSTRAINT chk_phone_unbound CHECK((status=1 AND unbound_at IS NULL) OR(status=2 AND unbound_at IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户手机号绑定及历史';

CREATE TABLE user_devices (
    id BIGINT NOT NULL COMMENT '设备编号',
    user_id BIGINT NOT NULL COMMENT '用户编号',
    installation_id_hash BINARY(32) NOT NULL COMMENT '安装摘要',
    device_name VARCHAR(128) NOT NULL COMMENT '设备名称',
    platform_code VARCHAR(32) NOT NULL COMMENT '平台编码',
    os_version VARCHAR(64) NULL COMMENT '系统版本',
    app_version VARCHAR(64) NULL COMMENT '应用版本',
    region_code VARCHAR(32) NULL COMMENT '地区编码',
    status TINYINT NOT NULL COMMENT '状态',
    first_seen_at DATETIME(3) NOT NULL COMMENT '首次时间',
    last_seen_at DATETIME(3) NOT NULL COMMENT '最近时间',
    status_changed_at DATETIME(3) NOT NULL COMMENT '变更时间',
    created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL COMMENT '更新时间',
    PRIMARY KEY(id),
    UNIQUE KEY uk_user_device_installation(user_id,
        installation_id_hash),
    KEY idx_device_user_status_seen(user_id,
        status,
        last_seen_at,
        id),
    CONSTRAINT fk_device_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_device_status CHECK(status IN(1,
        2,
        3)),
    CONSTRAINT chk_device_seen CHECK(last_seen_at>=first_seen_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户安装实例和设备状态';

CREATE TABLE user_login_sessions (
    id BIGINT NOT NULL COMMENT '会话编号',
    user_id BIGINT NOT NULL COMMENT '用户编号',
    device_id BIGINT NOT NULL COMMENT '设备编号',
    session_key VARCHAR(128) NOT NULL COMMENT '会话键',
    refresh_token_hash BINARY(32) NOT NULL COMMENT '刷新令牌摘要',
    refresh_token_version INT NOT NULL COMMENT '令牌版本',
    status TINYINT NOT NULL COMMENT '状态',
    expires_at DATETIME(3) NOT NULL COMMENT '过期时间',
    last_used_at DATETIME(3) NULL COMMENT '最近使用',
    revoked_at DATETIME(3) NULL COMMENT '撤销时间',
    revoke_reason VARCHAR(64) NULL COMMENT '撤销原因',
    version INT NOT NULL COMMENT '版本',
    created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL COMMENT '更新时间',
    active_device_id BIGINT GENERATED ALWAYS AS(IF(status=1,
        device_id,
        NULL)) STORED COMMENT '有效设备',
    PRIMARY KEY(id),
    UNIQUE KEY uk_session_key(session_key),
    UNIQUE KEY uk_session_refresh_hash(refresh_token_hash),
    UNIQUE KEY uk_session_active_device(active_device_id),
    KEY idx_session_user_status_expire(user_id,
        status,
        expires_at,
        id),
    KEY idx_session_device_status_created(device_id,
        status,
        created_at,
        id),
    CONSTRAINT fk_session_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_session_device FOREIGN KEY(device_id) REFERENCES user_devices(id) ON DELETE RESTRICT,
    CONSTRAINT chk_session_status CHECK(status IN(1,
        2,
        3)),
    CONSTRAINT chk_session_refresh_version CHECK(refresh_token_version>=0),
    CONSTRAINT chk_session_version CHECK(version>=0),
    CONSTRAINT chk_session_expire CHECK(expires_at>created_at),
    CONSTRAINT chk_session_revoked CHECK((status=2 AND revoked_at IS NOT NULL) OR(status<>2 AND revoked_at IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='刷新会话、轮换和撤销';

CREATE TABLE agreements (
    id BIGINT NOT NULL COMMENT '协议编号',
    agreement_type TINYINT NOT NULL COMMENT '协议类型',
    version_code VARCHAR(64) NOT NULL COMMENT '版本编码',
    title VARCHAR(255) NOT NULL COMMENT '标题',
    content LONGTEXT NOT NULL COMMENT '正文',
    content_hash BINARY(32) NOT NULL COMMENT '摘要',
    status TINYINT NOT NULL COMMENT '状态',
    requires_reconsent TINYINT NOT NULL COMMENT '是否重同意',
    scheduled_at DATETIME(3) NULL COMMENT '计划时间',
    effective_at DATETIME(3) NULL COMMENT '生效时间',
    retired_at DATETIME(3) NULL COMMENT '废止时间',
    created_by_admin_id BIGINT NULL COMMENT '创建管理员编号',
    version INT NOT NULL COMMENT '版本',
    created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL COMMENT '更新时间',
    active_agreement_type TINYINT GENERATED ALWAYS AS(IF(status=3,
        agreement_type,
        NULL)) STORED COMMENT '生效类型',
    PRIMARY KEY(id),
    UNIQUE KEY uk_agreement_type_version(agreement_type,
        version_code),
    UNIQUE KEY uk_agreement_effective_type(active_agreement_type),
    KEY idx_agreement_type_status_effective(agreement_type,
        status,
        effective_at,
        id),
    CONSTRAINT chk_agreement_type CHECK(agreement_type IN(1,
        2)),
    CONSTRAINT chk_agreement_status CHECK(status IN(1,
        2,
        3,
        4)),
    CONSTRAINT chk_agreement_reconsent CHECK(requires_reconsent IN(0,
        1)),
    CONSTRAINT chk_agreement_version CHECK(version>=0),
    CONSTRAINT chk_agreement_effective CHECK((status=3 AND effective_at IS NOT NULL) OR(status<>3 AND effective_at IS NULL)),
    CONSTRAINT chk_agreement_retired CHECK((status=4 AND retired_at IS NOT NULL) OR(status<>4 AND retired_at IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='协议与隐私政策版本正文';

CREATE TABLE agreement_consents (
    id BIGINT NOT NULL COMMENT '同意编号',
    user_id BIGINT NOT NULL COMMENT '用户编号',
    agreement_id BIGINT NOT NULL COMMENT '协议编号',
    agreed_at DATETIME(3) NOT NULL COMMENT '同意时间',
    request_id VARCHAR(64) NULL COMMENT '请求编号',
    ip_address_ciphertext VARBINARY(1024) NULL COMMENT '加密地址',
    client_version VARCHAR(64) NULL COMMENT '客户端版本',
    user_agent_summary VARCHAR(512) NULL COMMENT '客户端摘要',
    created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    PRIMARY KEY(id),
    UNIQUE KEY uk_consent_user_agreement(user_id,
        agreement_id),
    KEY idx_consent_user_agreed(user_id,
        agreed_at,
        id),
    CONSTRAINT fk_consent_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_consent_agreement FOREIGN KEY(agreement_id) REFERENCES agreements(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户同意具体协议版本的事实';

CREATE TABLE user_profiles (
    user_id BIGINT NOT NULL COMMENT '用户编号',
    nickname VARCHAR(20) NULL COMMENT '昵称',
    avatar_file_id BIGINT NULL COMMENT '头像文件编号',
    birth_date_ciphertext VARBINARY(1024) NULL COMMENT '加密生日',
    gender_code TINYINT NULL COMMENT '性别',
    province_code VARCHAR(32) NULL COMMENT '省编码',
    province_name VARCHAR(64) NULL COMMENT '省名',
    city_code VARCHAR(32) NULL COMMENT '市编码',
    city_name VARCHAR(64) NULL COMMENT '市名',
    district_code VARCHAR(32) NULL COMMENT '区县编码',
    district_name VARCHAR(64) NULL COMMENT '区县名',
    bio VARCHAR(500) NULL COMMENT '简介',
    completed_at DATETIME(3) NULL COMMENT '完成时间',
    nickname_changed_at DATETIME(3) NULL COMMENT '昵称修改时间',
    version INT NOT NULL COMMENT '版本',
    created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL COMMENT '更新时间',
    PRIMARY KEY(user_id),
    KEY idx_profile_region(province_code,
        city_code,
        district_code,
        user_id),
    CONSTRAINT fk_profile_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_profile_avatar FOREIGN KEY(avatar_file_id) REFERENCES file_objects(id) ON DELETE RESTRICT,
    CONSTRAINT chk_profile_nickname CHECK(nickname IS NULL OR CHAR_LENGTH(TRIM(nickname)) BETWEEN 2 AND 20),
    CONSTRAINT chk_profile_gender CHECK(gender_code IS NULL OR gender_code IN(1,
        2,
        3)),
    CONSTRAINT chk_profile_version CHECK(version>=0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户资料和完成状态';

CREATE TABLE interest_tags (
    id BIGINT NOT NULL COMMENT '标签编号',
    tag_code VARCHAR(64) NOT NULL COMMENT '编码',
    tag_name VARCHAR(64) NOT NULL COMMENT '名称',
    sort_order INT NOT NULL COMMENT '排序',
    status TINYINT NOT NULL COMMENT '状态',
    created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL COMMENT '更新时间',
    PRIMARY KEY(id),
    UNIQUE KEY uk_interest_tag_code(tag_code),
    UNIQUE KEY uk_interest_tag_name(tag_name),
    KEY idx_interest_status_sort(status,
        sort_order,
        id),
    CONSTRAINT chk_interest_status CHECK(status IN(1,
        2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='兴趣标签目录';

CREATE TABLE user_interest_tags (
    id BIGINT NOT NULL COMMENT '关系编号',
    user_id BIGINT NOT NULL COMMENT '用户编号',
    interest_tag_id BIGINT NOT NULL COMMENT '标签编号',
    selected_at DATETIME(3) NOT NULL COMMENT '选择时间',
    PRIMARY KEY(id),
    UNIQUE KEY uk_user_interest(user_id,
        interest_tag_id),
    KEY idx_user_interest_tag_user(interest_tag_id,
        user_id),
    CONSTRAINT fk_user_interest_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_user_interest_tag FOREIGN KEY(interest_tag_id) REFERENCES interest_tags(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户兴趣标签关系';

CREATE TABLE user_profile_change_logs (
    id BIGINT NOT NULL COMMENT '日志编号',
    user_id BIGINT NOT NULL COMMENT '用户编号',
    field_code VARCHAR(64) NOT NULL COMMENT '字段编码',
    old_value_ciphertext VARBINARY(2048) NULL COMMENT '旧值',
    new_value_ciphertext VARBINARY(2048) NULL COMMENT '新值',
    source_type TINYINT NOT NULL COMMENT '来源',
    actor_user_id BIGINT NULL COMMENT '操作用户编号',
    actor_admin_id BIGINT NULL COMMENT '操作管理员编号',
    reason VARCHAR(255) NULL COMMENT '原因',
    request_id VARCHAR(64) NULL COMMENT '请求编号',
    created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    PRIMARY KEY(id),
    KEY idx_profile_log_user_field_created(user_id,
        field_code,
        created_at,
        id),
    KEY idx_profile_log_request(request_id),
    CONSTRAINT fk_profile_log_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_profile_log_source CHECK(source_type IN(1,
        2,
        3))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='受限资料变更审计';

CREATE TABLE user_data_requests (
    id BIGINT NOT NULL COMMENT '请求编号',
    user_id BIGINT NOT NULL COMMENT '用户编号',
    request_type TINYINT NOT NULL COMMENT '类型',
    status TINYINT NOT NULL COMMENT '状态',
    requested_at DATETIME(3) NOT NULL COMMENT '申请时间',
    execute_after DATETIME(3) NOT NULL COMMENT '最早执行时间',
    result_file_id BIGINT NULL COMMENT '结果文件',
    result_expires_at DATETIME(3) NULL COMMENT '结果过期时间',
    retry_count INT NOT NULL COMMENT '重试数',
    failure_code VARCHAR(64) NULL COMMENT '失败编码',
    last_error_summary VARCHAR(512) NULL COMMENT '错误摘要',
    processed_at DATETIME(3) NULL COMMENT '处理时间',
    version INT NOT NULL COMMENT '版本',
    created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL COMMENT '更新时间',
    active_request_type TINYINT GENERATED ALWAYS AS(IF(status IN(1,
        2,
        3,
        6),
        request_type,
        NULL)) STORED COMMENT '未结束类型',
    PRIMARY KEY(id),
    UNIQUE KEY uk_data_request_active(user_id,
        active_request_type),
    KEY idx_data_request_status_execute(status,
        execute_after,
        id),
    CONSTRAINT fk_data_request_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_data_request_file FOREIGN KEY(result_file_id) REFERENCES file_objects(id) ON DELETE RESTRICT,
    CONSTRAINT chk_data_request_type CHECK(request_type IN(1,
        2)),
    CONSTRAINT chk_data_request_status CHECK(status IN(1,
        2,
        3,
        4,
        5,
        6)),
    CONSTRAINT chk_data_request_retry CHECK(retry_count>=0),
    CONSTRAINT chk_data_request_version CHECK(version>=0),
    CONSTRAINT chk_data_request_execute CHECK(execute_after>=requested_at),
    CONSTRAINT chk_data_request_wait CHECK(request_type<>1 OR execute_after=DATE_ADD(requested_at,
    INTERVAL 7 DAY))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='账号注销与数据导出请求主体';

CREATE TABLE user_data_request_events (
    id BIGINT NOT NULL COMMENT '事件编号',
    request_id BIGINT NOT NULL COMMENT '请求编号',
    event_type VARCHAR(64) NOT NULL COMMENT '事件类型',
    from_status TINYINT NULL COMMENT '原状态',
    to_status TINYINT NULL COMMENT '目标状态',
    actor_type TINYINT NOT NULL COMMENT '执行者',
    actor_id BIGINT NULL COMMENT '执行者编号',
    result_code VARCHAR(64) NULL COMMENT '结果',
    detail_json JSON NULL COMMENT '详情',
    trace_request_id VARCHAR(64) NULL COMMENT '链路编号',
    created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    PRIMARY KEY(id),
    KEY idx_request_event_request_created(request_id,
        created_at,
        id),
    KEY idx_request_event_trace(trace_request_id),
    CONSTRAINT fk_request_event_request FOREIGN KEY(request_id) REFERENCES user_data_requests(id) ON DELETE RESTRICT,
    CONSTRAINT chk_request_event_from CHECK(from_status IS NULL OR from_status IN(1,
        2,
        3,
        4,
        5,
        6)),
    CONSTRAINT chk_request_event_to CHECK(to_status IS NULL OR to_status IN(1,
        2,
        3,
        4,
        5,
        6)),
    CONSTRAINT chk_request_event_actor CHECK(actor_type IN(1,
        2,
        3))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='数据请求状态流转和执行事件';

CREATE TABLE account_security_events (
    id BIGINT NOT NULL COMMENT '事件编号',
    user_id BIGINT NOT NULL COMMENT '用户编号',
    device_id BIGINT NULL COMMENT '设备编号',
    session_id BIGINT NULL COMMENT '会话编号',
    event_type VARCHAR(64) NOT NULL COMMENT '事件类型',
    severity TINYINT NOT NULL COMMENT '风险等级',
    region_code VARCHAR(32) NULL COMMENT '地区编码',
    ip_lookup_hash BINARY(32) NULL COMMENT '网络地址摘要',
    detail_json JSON NULL COMMENT '详情',
    notified_at DATETIME(3) NULL COMMENT '通知时间',
    occurred_at DATETIME(3) NOT NULL COMMENT '发生时间',
    created_at DATETIME(3) NOT NULL COMMENT '创建时间',
    PRIMARY KEY(id),
    KEY idx_security_user_occurred(user_id,
        occurred_at,
        id),
    KEY idx_security_type_severity_occurred(event_type,
        severity,
        occurred_at,
        id),
    CONSTRAINT fk_security_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_security_device FOREIGN KEY(device_id) REFERENCES user_devices(id) ON DELETE RESTRICT,
    CONSTRAINT fk_security_session FOREIGN KEY(session_id) REFERENCES user_login_sessions(id) ON DELETE RESTRICT,
    CONSTRAINT chk_security_severity CHECK(severity IN(1,
        2,
        3))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='登录和账号安全事件';
